-- 010: GCP US 와 schema 정합 — agents에 5개 컬럼 추가
ALTER TABLE agents ADD COLUMN IF NOT EXISTS allowed_tools TEXT[];
ALTER TABLE agents ADD COLUMN IF NOT EXISTS context_size  INTEGER;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_free       BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS model_name    VARCHAR(50);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS model_version VARCHAR(50);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO masterplan;
