#!/usr/bin/env node
/**
 * load-secrets.mjs — GCP Secret Manager에서 secret을 로드하여 .env.local 생성
 *
 * 정본: PRD-Platform 결정 6 + ENGINEERING-GUIDE §8.6 + PRD-OpenAgentX §9 결정 28
 *
 * 사용:
 *   GOOGLE_APPLICATION_CREDENTIALS=/etc/openagentx/sa.json node scripts/load-secrets.mjs
 *
 * 환경변수:
 *   GOOGLE_APPLICATION_CREDENTIALS  서비스 계정 JSON key 경로
 *   GCP_PROJECT_ID                  프로젝트 ID (기본: teeup-492907)
 *   OPENAGENTX_SECRET_PREFIX        Secret name prefix (기본: OPENAGENTX_)
 *   OUT_PATH                        출력 .env 파일 경로 (기본: .env.local)
 *
 * Secret 이름 매핑 (GCP Secret Manager) → .env key:
 *   OPENAGENTX_NEXTAUTH_SECRET              → NEXTAUTH_SECRET
 *   OPENAGENTX_ANTHROPIC_API_KEY            → ANTHROPIC_API_KEY
 *   OPENAGENTX_GOOGLE_AI_API_KEY            → GOOGLE_AI_API_KEY
 *   OPENAGENTX_INNGEST_EVENT_KEY            → INNGEST_EVENT_KEY
 *   OPENAGENTX_INNGEST_SIGNING_KEY          → INNGEST_SIGNING_KEY
 *   OPENAGENTX_PLATFORM_WALLET_PRIVATE_KEY  → PLATFORM_WALLET_PRIVATE_KEY
 *   OPENAGENTX_TELEGRAM_BOT_TOKEN           → TELEGRAM_BOT_TOKEN
 *   OPENAGENTX_TELEGRAM_CHAT_ID             → TELEGRAM_CHAT_ID
 *   OPENAGENTX_PORTONE_API_SECRET           → PORTONE_API_SECRET
 *   OPENAGENTX_PORTONE_STORE_ID             → NEXT_PUBLIC_PORTONE_STORE_ID
 *   OPENAGENTX_PORTONE_CHANNEL_KEY_CARD     → NEXT_PUBLIC_PORTONE_CHANNEL_KEY_CARD
 *   OPENAGENTX_PORTONE_CHANNEL_KEY_KAKAOPAY → NEXT_PUBLIC_PORTONE_CHANNEL_KEY_KAKAOPAY
 *   OPENAGENTX_PORTONE_CHANNEL_KEY_TOSSPAY  → NEXT_PUBLIC_PORTONE_CHANNEL_KEY_TOSSPAY
 *   OPENAGENTX_PORTONE_CHANNEL_KEY_NAVERPAY → NEXT_PUBLIC_PORTONE_CHANNEL_KEY_NAVERPAY
 *   OPENAGENTX_ADMIN_EMAIL                  → ADMIN_EMAIL
 *
 * 로컬 전용 (Secret Manager에 두지 않는 값):
 *   DATABASE_URL, REDIS_*, NEXTAUTH_URL, BASE_RPC_URL — .env.local.local 또는 직접 작성
 */
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const PROJECT_ID = process.env.GCP_PROJECT_ID || 'teeup-492907';
const PREFIX = process.env.OPENAGENTX_SECRET_PREFIX || 'OPENAGENTX_';
const OUT = process.env.OUT_PATH || '.env.local';

const SECRET_TO_ENV = {
  NEXTAUTH_SECRET:             'NEXTAUTH_SECRET',
  ANTHROPIC_API_KEY:           'ANTHROPIC_API_KEY',
  GOOGLE_AI_API_KEY:           'GOOGLE_AI_API_KEY',
  INNGEST_EVENT_KEY:           'INNGEST_EVENT_KEY',
  INNGEST_SIGNING_KEY:         'INNGEST_SIGNING_KEY',
  PLATFORM_WALLET_PRIVATE_KEY: 'PLATFORM_WALLET_PRIVATE_KEY',
  TELEGRAM_BOT_TOKEN:          'TELEGRAM_BOT_TOKEN',
  TELEGRAM_CHAT_ID:            'TELEGRAM_CHAT_ID',
  PORTONE_API_SECRET:          'PORTONE_API_SECRET',
  PORTONE_STORE_ID:            'NEXT_PUBLIC_PORTONE_STORE_ID',
  PORTONE_CHANNEL_KEY_CARD:    'NEXT_PUBLIC_PORTONE_CHANNEL_KEY_CARD',
  PORTONE_CHANNEL_KEY_KAKAOPAY:'NEXT_PUBLIC_PORTONE_CHANNEL_KEY_KAKAOPAY',
  PORTONE_CHANNEL_KEY_TOSSPAY: 'NEXT_PUBLIC_PORTONE_CHANNEL_KEY_TOSSPAY',
  PORTONE_CHANNEL_KEY_NAVERPAY:'NEXT_PUBLIC_PORTONE_CHANNEL_KEY_NAVERPAY',
  ADMIN_EMAIL:                 'ADMIN_EMAIL',
};

// Local-only values (not stored in Secret Manager)
const LOCAL_DEFAULTS = {
  DATABASE_URL: 'postgresql://cryptointel:cryptointel@localhost:5434/cryptointel',
  REDIS_HOST: 'localhost',
  REDIS_PORT: '6379',
  REDIS_DB: '1',
  NEXTAUTH_URL: 'https://openagentx.org',
  BASE_RPC_URL: 'https://mainnet.base.org',
};

async function main() {
  if (!process.env.GOOGLE_APPLICATION_CREDENTIALS) {
    console.error('[secrets] GOOGLE_APPLICATION_CREDENTIALS not set');
    console.error('[secrets] Run: GOOGLE_APPLICATION_CREDENTIALS=/etc/openagentx/sa.json node scripts/load-secrets.mjs');
    process.exit(1);
  }

  const client = new SecretManagerServiceClient();
  const env = { ...LOCAL_DEFAULTS };
  const missing = [];

  for (const [secretSuffix, envKey] of Object.entries(SECRET_TO_ENV)) {
    const name = `projects/${PROJECT_ID}/secrets/${PREFIX}${secretSuffix}/versions/latest`;
    try {
      const [v] = await client.accessSecretVersion({ name });
      env[envKey] = v.payload.data.toString('utf8').replace(/\r?\n$/, '');
      console.log(`[secrets] ✓ ${PREFIX}${secretSuffix} → ${envKey}`);
    } catch (e) {
      missing.push(`${PREFIX}${secretSuffix}`);
      console.warn(`[secrets] ✗ ${PREFIX}${secretSuffix}: ${e.code || e.message}`);
    }
  }

  // Render .env.local
  const lines = [
    `# Generated by load-secrets.mjs at ${new Date().toISOString()}`,
    `# Source: GCP Secret Manager (project=${PROJECT_ID}, prefix=${PREFIX})`,
    '',
  ];
  for (const [k, v] of Object.entries(env)) {
    // Quote if contains spaces or special chars
    const quoted = /[\s"'$`#=]/.test(v) ? `"${v.replace(/"/g, '\\"')}"` : v;
    lines.push(`${k}=${quoted}`);
  }
  writeFileSync(resolve(OUT), lines.join('\n') + '\n', { mode: 0o600 });
  console.log(`[secrets] wrote ${OUT} (${Object.keys(env).length} keys)`);

  if (missing.length) {
    console.warn(`[secrets] ${missing.length} secret(s) missing — register with:`);
    for (const m of missing) {
      console.warn(`  gcloud secrets create ${m} --data-file=<file>`);
    }
    process.exit(2);
  }
}

main().catch((e) => {
  console.error('[secrets] fatal:', e);
  process.exit(1);
});
